### ISSUE TITLE
Game of drones leaderboard link

### ISSUE THREAD

**Issue by eulerscheZahl** [Azkellas/cgmulti#1]
The link to the game of drones leaderboard leads nowhere, you forgot an 's'.

**Comment by Azkellas** [comment]
Sorry I missed this issue. CG oddly uses a different name for Game of Drones (game-of-drone for API, game-of-drones for URL). Anyway this should be fixed now. Thanks for reporting. :)

**Comment by eulerscheZahl** [comment]
Try to parse the Tron contest leaderboard, if you want to see strange URLs :stuck_out_tongue:
